controller_manager:
  ros__parameters:
    update_rate: 1000   # <-- sÃºbelo a 1000 Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_velocity_controller:
      type: forward_command_controller/ForwardCommandController

motor_velocity_controller:
  ros__parameters:
    interface_name: velocity
    joints: [simple_motor]
